process.env.DATABASE_HOST ??= "localhost"
process.env.DATABASE_PORT ??= "5432"
process.env.DATABASE_NAME ??= "odonto"
process.env.DATABASE_USER ??= "postgres"
process.env.DATABASE_PASSWORD ??= "postgres"
process.env.CLERK_SECRET_KEY ??= "sk_test_123"
